### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by MarioPossamato** [ic-scm/openrevolution#4]
Whenever I try to build the player by running `sh build.sh`, I receive this output:
```
Building player...
/opt/devkitpro/msys2/usr/bin/../lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lrtaudio
collect2: error: ld returned 1 exit status
Building converter...
```
Any help on this issue would be greatly appreciated!

**Comment by MarioPossamato** [comment]
Ah, I figured out my mistake; I completely forgot to get librtaudio!  Sorry for my stupidity :P

**Comment by FreeApp2014** [comment]
> The linked file is an archlinux package, I don't know if it's possible to just copy the files from that into your environment and have it working like that. See if the documentation for your msys2 environment mentions anything about installing libraries, and if you have a package manager, check if you can get an rtaudio package from the repositories of your package manager. You probably don't need to worry about using my forked version of rtaudio, it fixes an issue that seems to be specific only to Linux systems using the Pulseaudio sound system.

No, it doesn't quite work like that

MinGW works with native Windows binaries, and not Linux binaries 

Additionally, these binaries as mentioned are linked against Pulseaudio/Alsa and not WASAPI/Directsound

You should pull rtaudio from git and build it in MinGW.
For me it was a quite flakey experience but i think what worked in the end was the Cmake build flow. 

I can try to find my compiled .dll and .dll.a files that worked for me.

**Comment by FreeApp2014** [comment]
> I can try to find my compiled .dll and .dll.a files that worked for me. 

Okay I think I found them and put them to a zip [https://cdn.discordapp.com/attachments/283672598196518912/826943110792609807/Archive.zip](https://cdn.discordapp.com/attachments/283672598196518912/826943110792609807/Archive.zip)

As far as I remember what you basically do is you place these files to the location where the main cop file is, and instead of using `-lrtaudio` you put `librtaudio.dll.a` as a second file name

**Comment by MarioPossamato** [comment]
Thank you! :D  Also, please pardon my ineptitude on this particular topic (I'm not that familiar with this stuff); what do you mean by main cop file?

**Comment by FreeApp2014** [comment]
> Thank you! :D  Also, please pardon my ineptitude on this particular topic (I'm not that familiar with this stuff); what do you mean by main cop file?

Oh, sorry, I am on my phone, autocorrect popped in without me noticing. I meant "a CPP file"

**Comment by MarioPossamato** [comment]
Ah, ok, no problem!  Thanks again! :)
